#%RAML 1.0 DataType
type: object
properties:
  id:
    type: string
    description: User id
  name:
    type: string
    description: User name
  email:
    type: string
    description: User email
  createdDate:
    type: datetime
    description: Created date
  updatedDate:
    type: datetime
    description: Created date
